# создаем пользователя для проэкта

CREATE USER 'art-root'@'localhost' IDENTIFIED BY '12345678';
GRANT USAGE ON *.* TO 'art-root'@'localhost';
GRANT SELECT, SHOW VIEW, EXECUTE, ALTER, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES, CREATE  ON `art`.* TO 'art-root'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

